-- PostgreSQL 18 New Features


-- UUIDv7 (timestamp-ordered UUIDs)

SELECT uuidv7();
-- Returns: 019470a8-1234-7abc-8def-012345678901

-- Use in table
CREATE TABLE orders (
  id uuid PRIMARY KEY DEFAULT uuidv7(),
  total numeric NOT NULL
);


-- Asynchronous I/O configuration

-- Check current settings
SHOW io_method;             -- worker (default), io_uring, or sync
SHOW io_workers;            -- default 3
SHOW effective_io_concurrency;
SHOW maintenance_io_concurrency;

-- Recommended production settings
ALTER SYSTEM SET io_method = 'worker';
ALTER SYSTEM SET io_workers = 12;  -- ~1/4 of CPU cores
ALTER SYSTEM SET effective_io_concurrency = 32;
ALTER SYSTEM SET maintenance_io_concurrency = 16;


-- RETURNING OLD and NEW values

-- UPDATE with OLD/NEW access
UPDATE inventory
SET quantity = quantity - 10
WHERE product_id = 123
RETURNING OLD.quantity AS was, NEW.quantity AS now;

-- DELETE with OLD access
DELETE FROM audit_log
WHERE created_at < now() - interval '90 days'
RETURNING OLD.*;

-- MERGE with RETURNING
MERGE INTO products t
USING staging s ON t.sku = s.sku
WHEN MATCHED THEN
  UPDATE SET price = s.price
WHEN NOT MATCHED THEN
  INSERT (sku, name, price) VALUES (s.sku, s.name, s.price)
RETURNING *;


-- Virtual generated columns (computed at read time)

CREATE TABLE products (
  price numeric NOT NULL,
  tax_rate numeric NOT NULL,

  -- Stored (on disk, can be indexed)
  total_price numeric GENERATED ALWAYS AS (price * (1 + tax_rate)) STORED,

  -- Virtual (computed at read, not stored)
  display_price text GENERATED ALWAYS AS (price::text || ' USD')
);


-- Temporal constraints (WITHOUT OVERLAPS)

CREATE TABLE room_bookings (
  room_id int,
  booking_period tstzrange,
  guest_name text,
  PRIMARY KEY (room_id, booking_period WITHOUT OVERLAPS)
);

-- Prevents overlapping bookings for same room
INSERT INTO room_bookings VALUES (1, '[2024-01-01, 2024-01-05)', 'Alice');
INSERT INTO room_bookings VALUES (1, '[2024-01-03, 2024-01-07)', 'Bob');
-- ERROR: conflicting key value violates exclusion constraint


-- Index skip scan (automatic, no config needed)

-- Index on (region, status, created_at)
CREATE INDEX orders_region_status_date ON orders(region, status, created_at);

-- This query now uses skip scan even without region filter
SELECT * FROM orders WHERE status = 'pending';
-- ~40% faster than full table scan


-- Data checksums (enabled by default in PG18)

SHOW data_checksums;  -- on

-- Verify page checksums
SELECT datname, checksum_failures FROM pg_stat_database;


-- Identity columns (preferred over SERIAL)

CREATE TABLE users (
  -- GENERATED ALWAYS (recommended)
  id int GENERATED ALWAYS AS IDENTITY PRIMARY KEY,

  -- GENERATED BY DEFAULT (allows manual override)
  legacy_id int GENERATED BY DEFAULT AS IDENTITY,

  name text NOT NULL
);

-- With sequence options
CREATE TABLE events (
  id int GENERATED ALWAYS AS IDENTITY (
    START WITH 1000
    INCREMENT BY 1
    MINVALUE 1
    MAXVALUE 2147483647
    CACHE 100
  ) PRIMARY KEY
);


-- COPY FROM with error handling (PG18)

COPY users FROM '/data/users.csv'
WITH (
  FORMAT csv,
  HEADER true,
  ON_ERROR 'ignore',  -- Skip bad rows
  LOG_VERBOSITY 'verbose'
);
